# railway.toml

[build]
builder = "NIXPACKS"
nixPkgs = ["ffmpeg"]  # Liste des paquets Nix à installer

[deploy]
region = "us-west2"
runtime = "V2"
numReplicas = 1
startCommand = "python bot.py"
sleepApplication = false

[multiRegionConfig]
  [multiRegionConfig.us-west2]
  numReplicas = 1

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
