[build]
builder = "NIXPACKS"
buildCommand = "[phases.setup] nixPkgs = ['ffmpeg']"

[deploy]
region = "us-west2"
runtime = "V2"
numReplicas = 1
startCommand = "python bot.py"
sleepApplication = false

[multiRegionConfig]
  [multiRegionConfig.us-west2]
  numReplicas = 1

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
